// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpCloudInfragraph20250507EdgeQuery hashicorp cloud infragraph 20250507 edge query
//
// swagger:model hashicorp.cloud.infragraph_20250507.EdgeQuery
type HashicorpCloudInfragraph20250507EdgeQuery struct {

	// absent specifies whether to find edges that exist or do not exist. If true, the query will return nodes that do not have the described edge.
	Absent bool `json:"absent,omitempty"`

	// direction specifies whether to include incoming, outgoing, or both edge directions in the query.
	Direction *HashicorpCloudInfragraph20250507EdgeDirection `json:"direction,omitempty"`

	// edge_types is the verb specifying the relationship to the next node (e.g. “Produces”). It can be a single label or a set of labels. Wildcard returns all edges.
	EdgeTypes []string `json:"edge_types"`

	// node_query specifies the next set of nodes to traverse in the query.
	NodeQuery *HashicorpCloudInfragraph20250507NodeQuery `json:"node_query,omitempty"`
}

// Validate validates this hashicorp cloud infragraph 20250507 edge query
func (m *HashicorpCloudInfragraph20250507EdgeQuery) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDirection(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNodeQuery(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudInfragraph20250507EdgeQuery) validateDirection(formats strfmt.Registry) error {
	if swag.IsZero(m.Direction) { // not required
		return nil
	}

	if m.Direction != nil {
		if err := m.Direction.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("direction")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("direction")
			}
			return err
		}
	}

	return nil
}

func (m *HashicorpCloudInfragraph20250507EdgeQuery) validateNodeQuery(formats strfmt.Registry) error {
	if swag.IsZero(m.NodeQuery) { // not required
		return nil
	}

	if m.NodeQuery != nil {
		if err := m.NodeQuery.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("node_query")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("node_query")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this hashicorp cloud infragraph 20250507 edge query based on the context it is used
func (m *HashicorpCloudInfragraph20250507EdgeQuery) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDirection(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNodeQuery(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudInfragraph20250507EdgeQuery) contextValidateDirection(ctx context.Context, formats strfmt.Registry) error {

	if m.Direction != nil {

		if swag.IsZero(m.Direction) { // not required
			return nil
		}

		if err := m.Direction.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("direction")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("direction")
			}
			return err
		}
	}

	return nil
}

func (m *HashicorpCloudInfragraph20250507EdgeQuery) contextValidateNodeQuery(ctx context.Context, formats strfmt.Registry) error {

	if m.NodeQuery != nil {

		if swag.IsZero(m.NodeQuery) { // not required
			return nil
		}

		if err := m.NodeQuery.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("node_query")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("node_query")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudInfragraph20250507EdgeQuery) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudInfragraph20250507EdgeQuery) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudInfragraph20250507EdgeQuery
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
