// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpCloudInfragraph20250507DomainAzurePrivateDNSZone AzurePrivateDnsZone domain model message.
//
// swagger:model hashicorp.cloud.infragraph_20250507.domain.AzurePrivateDnsZone
type HashicorpCloudInfragraph20250507DomainAzurePrivateDNSZone struct {

	// azure resource
	AzureResource *HashicorpCloudInfragraph20250507DomainAzureResource `json:"azure_resource,omitempty"`

	// inherited types
	DNSZone *HashicorpCloudInfragraph20250507DomainBaseDNSZone `json:"dns_zone,omitempty"`

	// Private DNS Zone-specific properties - current counts only
	NumberOfRecordSets *string `json:"number_of_record_sets,omitempty"`

	// number of virtual network links
	NumberOfVirtualNetworkLinks *string `json:"number_of_virtual_network_links,omitempty"`

	// number of virtual network links with registration
	NumberOfVirtualNetworkLinksWithRegistration *string `json:"number_of_virtual_network_links_with_registration,omitempty"`

	// Azure resource group identifier that contains this private DNS zone.
	ResourceGroupID *string `json:"resource_group_id,omitempty"`
}

// Validate validates this hashicorp cloud infragraph 20250507 domain azure private Dns zone
func (m *HashicorpCloudInfragraph20250507DomainAzurePrivateDNSZone) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAzureResource(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDNSZone(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudInfragraph20250507DomainAzurePrivateDNSZone) validateAzureResource(formats strfmt.Registry) error {
	if swag.IsZero(m.AzureResource) { // not required
		return nil
	}

	if m.AzureResource != nil {
		if err := m.AzureResource.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("azure_resource")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("azure_resource")
			}
			return err
		}
	}

	return nil
}

func (m *HashicorpCloudInfragraph20250507DomainAzurePrivateDNSZone) validateDNSZone(formats strfmt.Registry) error {
	if swag.IsZero(m.DNSZone) { // not required
		return nil
	}

	if m.DNSZone != nil {
		if err := m.DNSZone.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dns_zone")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("dns_zone")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this hashicorp cloud infragraph 20250507 domain azure private Dns zone based on the context it is used
func (m *HashicorpCloudInfragraph20250507DomainAzurePrivateDNSZone) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAzureResource(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDNSZone(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudInfragraph20250507DomainAzurePrivateDNSZone) contextValidateAzureResource(ctx context.Context, formats strfmt.Registry) error {

	if m.AzureResource != nil {

		if swag.IsZero(m.AzureResource) { // not required
			return nil
		}

		if err := m.AzureResource.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("azure_resource")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("azure_resource")
			}
			return err
		}
	}

	return nil
}

func (m *HashicorpCloudInfragraph20250507DomainAzurePrivateDNSZone) contextValidateDNSZone(ctx context.Context, formats strfmt.Registry) error {

	if m.DNSZone != nil {

		if swag.IsZero(m.DNSZone) { // not required
			return nil
		}

		if err := m.DNSZone.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dns_zone")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("dns_zone")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudInfragraph20250507DomainAzurePrivateDNSZone) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudInfragraph20250507DomainAzurePrivateDNSZone) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudInfragraph20250507DomainAzurePrivateDNSZone
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
