// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpCloudInfragraph20250507DomainWorkloadPolicyDetails hashicorp cloud infragraph 20250507 domain workload policy details
//
// swagger:model hashicorp.cloud.infragraph_20250507.domain.WorkloadPolicyDetails
type HashicorpCloudInfragraph20250507DomainWorkloadPolicyDetails struct {

	// Whether compression is enabled (Workload only)
	IsCompression *bool `json:"is_compression,omitempty"`

	// Workload-specific properties (AzureWorkload: SQL/SAP)
	//
	// Minutes between log backups (Workload only)
	LogBackupFrequencyInMins *int32 `json:"log_backup_frequency_in_mins,omitempty"`

	// Days to retain log backups (Workload only)
	LogBackupRetentionDays *int32 `json:"log_backup_retention_days,omitempty"`

	// Months to retain monthly backups
	MonthlyRetentionCount *int32 `json:"monthly_retention_count,omitempty"`

	// Weeks to retain weekly backups
	WeeklyRetentionCount *int32 `json:"weekly_retention_count,omitempty"`

	// Years to retain yearly backups
	YearlyRetentionCount *int32 `json:"yearly_retention_count,omitempty"`
}

// Validate validates this hashicorp cloud infragraph 20250507 domain workload policy details
func (m *HashicorpCloudInfragraph20250507DomainWorkloadPolicyDetails) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud infragraph 20250507 domain workload policy details based on context it is used
func (m *HashicorpCloudInfragraph20250507DomainWorkloadPolicyDetails) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudInfragraph20250507DomainWorkloadPolicyDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudInfragraph20250507DomainWorkloadPolicyDetails) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudInfragraph20250507DomainWorkloadPolicyDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
