// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// HashicorpCloudInfragraph20250507Comparator Comparator is a type that allows users to compare propertyName and value when filtering for a specific value.
//
// swagger:model hashicorp.cloud.infragraph_20250507.Comparator
type HashicorpCloudInfragraph20250507Comparator string

func NewHashicorpCloudInfragraph20250507Comparator(value HashicorpCloudInfragraph20250507Comparator) *HashicorpCloudInfragraph20250507Comparator {
	return &value
}

// Pointer returns a pointer to a freshly-allocated HashicorpCloudInfragraph20250507Comparator.
func (m HashicorpCloudInfragraph20250507Comparator) Pointer() *HashicorpCloudInfragraph20250507Comparator {
	return &m
}

const (

	// HashicorpCloudInfragraph20250507ComparatorCOMPARATORUNSPECIFIED captures enum value "COMPARATOR_UNSPECIFIED"
	HashicorpCloudInfragraph20250507ComparatorCOMPARATORUNSPECIFIED HashicorpCloudInfragraph20250507Comparator = "COMPARATOR_UNSPECIFIED"

	// HashicorpCloudInfragraph20250507ComparatorEQUAL captures enum value "EQUAL"
	HashicorpCloudInfragraph20250507ComparatorEQUAL HashicorpCloudInfragraph20250507Comparator = "EQUAL"

	// HashicorpCloudInfragraph20250507ComparatorNOTEQUAL captures enum value "NOT_EQUAL"
	HashicorpCloudInfragraph20250507ComparatorNOTEQUAL HashicorpCloudInfragraph20250507Comparator = "NOT_EQUAL"

	// HashicorpCloudInfragraph20250507ComparatorGREATERTHAN captures enum value "GREATER_THAN"
	HashicorpCloudInfragraph20250507ComparatorGREATERTHAN HashicorpCloudInfragraph20250507Comparator = "GREATER_THAN"

	// HashicorpCloudInfragraph20250507ComparatorLESSTHAN captures enum value "LESS_THAN"
	HashicorpCloudInfragraph20250507ComparatorLESSTHAN HashicorpCloudInfragraph20250507Comparator = "LESS_THAN"

	// HashicorpCloudInfragraph20250507ComparatorGREATERTHANOREQUAL captures enum value "GREATER_THAN_OR_EQUAL"
	HashicorpCloudInfragraph20250507ComparatorGREATERTHANOREQUAL HashicorpCloudInfragraph20250507Comparator = "GREATER_THAN_OR_EQUAL"

	// HashicorpCloudInfragraph20250507ComparatorLESSTHANOREQUAL captures enum value "LESS_THAN_OR_EQUAL"
	HashicorpCloudInfragraph20250507ComparatorLESSTHANOREQUAL HashicorpCloudInfragraph20250507Comparator = "LESS_THAN_OR_EQUAL"

	// HashicorpCloudInfragraph20250507ComparatorEXISTS captures enum value "EXISTS"
	HashicorpCloudInfragraph20250507ComparatorEXISTS HashicorpCloudInfragraph20250507Comparator = "EXISTS"

	// HashicorpCloudInfragraph20250507ComparatorDOESNOTEXIST captures enum value "DOES_NOT_EXIST"
	HashicorpCloudInfragraph20250507ComparatorDOESNOTEXIST HashicorpCloudInfragraph20250507Comparator = "DOES_NOT_EXIST"

	// HashicorpCloudInfragraph20250507ComparatorIN captures enum value "IN"
	HashicorpCloudInfragraph20250507ComparatorIN HashicorpCloudInfragraph20250507Comparator = "IN"

	// HashicorpCloudInfragraph20250507ComparatorNOTIN captures enum value "NOT_IN"
	HashicorpCloudInfragraph20250507ComparatorNOTIN HashicorpCloudInfragraph20250507Comparator = "NOT_IN"

	// HashicorpCloudInfragraph20250507ComparatorSTARTSWITH captures enum value "STARTS_WITH"
	HashicorpCloudInfragraph20250507ComparatorSTARTSWITH HashicorpCloudInfragraph20250507Comparator = "STARTS_WITH"

	// HashicorpCloudInfragraph20250507ComparatorISNOTEMPTY captures enum value "IS_NOT_EMPTY"
	HashicorpCloudInfragraph20250507ComparatorISNOTEMPTY HashicorpCloudInfragraph20250507Comparator = "IS_NOT_EMPTY"
)

// for schema
var hashicorpCloudInfragraph20250507ComparatorEnum []interface{}

func init() {
	var res []HashicorpCloudInfragraph20250507Comparator
	if err := json.Unmarshal([]byte(`["COMPARATOR_UNSPECIFIED","EQUAL","NOT_EQUAL","GREATER_THAN","LESS_THAN","GREATER_THAN_OR_EQUAL","LESS_THAN_OR_EQUAL","EXISTS","DOES_NOT_EXIST","IN","NOT_IN","STARTS_WITH","IS_NOT_EMPTY"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		hashicorpCloudInfragraph20250507ComparatorEnum = append(hashicorpCloudInfragraph20250507ComparatorEnum, v)
	}
}

func (m HashicorpCloudInfragraph20250507Comparator) validateHashicorpCloudInfragraph20250507ComparatorEnum(path, location string, value HashicorpCloudInfragraph20250507Comparator) error {
	if err := validate.EnumCase(path, location, value, hashicorpCloudInfragraph20250507ComparatorEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this hashicorp cloud infragraph 20250507 comparator
func (m HashicorpCloudInfragraph20250507Comparator) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateHashicorpCloudInfragraph20250507ComparatorEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this hashicorp cloud infragraph 20250507 comparator based on context it is used
func (m HashicorpCloudInfragraph20250507Comparator) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
