// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpCloudConsul20200413ConsulConfig ConsulConfig exposes user settable configurations for a Consul cluster.
//
// swagger:model hashicorp.cloud.consul_20200413.ConsulConfig
type HashicorpCloudConsul20200413ConsulConfig struct {

	// connect_enabled toggles Consul Connect on the Consul servers.
	ConnectEnabled bool `json:"connect_enabled,omitempty"`

	// datacenter sets the datacenter the Consul servers will be running in. If
	// not set, a default value will be used.
	//
	// https://www.consul.io/docs/agent/options.html#datacenter
	Datacenter string `json:"datacenter,omitempty"`

	// initial_version is the initial Consul version to use when creating the
	// cluster. Once the cluster is created, this value is no longer used.
	InitialVersion string `json:"initial_version,omitempty"`

	// version is the current Consul version the server nodes are running.
	Version string `json:"version,omitempty"`
}

// Validate validates this hashicorp cloud consul 20200413 consul config
func (m *HashicorpCloudConsul20200413ConsulConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud consul 20200413 consul config based on context it is used
func (m *HashicorpCloudConsul20200413ConsulConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsul20200413ConsulConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsul20200413ConsulConfig) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsul20200413ConsulConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
