// Code generated by go-swagger; DO NOT EDIT.

package secret_manager_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/hashicorp/hcp-sdk-go/clients/cloud-vault-radar/preview/2023-05-01/models"
)

// PatchSecretManagerFeaturesReader is a Reader for the PatchSecretManagerFeatures structure.
type PatchSecretManagerFeaturesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchSecretManagerFeaturesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchSecretManagerFeaturesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPatchSecretManagerFeaturesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPatchSecretManagerFeaturesOK creates a PatchSecretManagerFeaturesOK with default headers values
func NewPatchSecretManagerFeaturesOK() *PatchSecretManagerFeaturesOK {
	return &PatchSecretManagerFeaturesOK{}
}

/*
PatchSecretManagerFeaturesOK describes a response with status code 200, with default header values.

A successful response.
*/
type PatchSecretManagerFeaturesOK struct {
	Payload interface{}
}

// IsSuccess returns true when this patch secret manager features o k response has a 2xx status code
func (o *PatchSecretManagerFeaturesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch secret manager features o k response has a 3xx status code
func (o *PatchSecretManagerFeaturesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch secret manager features o k response has a 4xx status code
func (o *PatchSecretManagerFeaturesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch secret manager features o k response has a 5xx status code
func (o *PatchSecretManagerFeaturesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch secret manager features o k response a status code equal to that given
func (o *PatchSecretManagerFeaturesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the patch secret manager features o k response
func (o *PatchSecretManagerFeaturesOK) Code() int {
	return 200
}

func (o *PatchSecretManagerFeaturesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /2023-05-01/vault-radar/projects/{location.project_id}/secret-managers/features][%d] patchSecretManagerFeaturesOK %s", 200, payload)
}

func (o *PatchSecretManagerFeaturesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /2023-05-01/vault-radar/projects/{location.project_id}/secret-managers/features][%d] patchSecretManagerFeaturesOK %s", 200, payload)
}

func (o *PatchSecretManagerFeaturesOK) GetPayload() interface{} {
	return o.Payload
}

func (o *PatchSecretManagerFeaturesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchSecretManagerFeaturesDefault creates a PatchSecretManagerFeaturesDefault with default headers values
func NewPatchSecretManagerFeaturesDefault(code int) *PatchSecretManagerFeaturesDefault {
	return &PatchSecretManagerFeaturesDefault{
		_statusCode: code,
	}
}

/*
PatchSecretManagerFeaturesDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PatchSecretManagerFeaturesDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this patch secret manager features default response has a 2xx status code
func (o *PatchSecretManagerFeaturesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this patch secret manager features default response has a 3xx status code
func (o *PatchSecretManagerFeaturesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this patch secret manager features default response has a 4xx status code
func (o *PatchSecretManagerFeaturesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this patch secret manager features default response has a 5xx status code
func (o *PatchSecretManagerFeaturesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this patch secret manager features default response a status code equal to that given
func (o *PatchSecretManagerFeaturesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the patch secret manager features default response
func (o *PatchSecretManagerFeaturesDefault) Code() int {
	return o._statusCode
}

func (o *PatchSecretManagerFeaturesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /2023-05-01/vault-radar/projects/{location.project_id}/secret-managers/features][%d] PatchSecretManagerFeatures default %s", o._statusCode, payload)
}

func (o *PatchSecretManagerFeaturesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /2023-05-01/vault-radar/projects/{location.project_id}/secret-managers/features][%d] PatchSecretManagerFeatures default %s", o._statusCode, payload)
}

func (o *PatchSecretManagerFeaturesDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *PatchSecretManagerFeaturesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
PatchSecretManagerFeaturesBody patch secret manager features body
swagger:model PatchSecretManagerFeaturesBody
*/
type PatchSecretManagerFeaturesBody struct {

	// features
	Features interface{} `json:"features,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// location
	Location *PatchSecretManagerFeaturesParamsBodyLocation `json:"location,omitempty"`
}

// Validate validates this patch secret manager features body
func (o *PatchSecretManagerFeaturesBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLocation(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PatchSecretManagerFeaturesBody) validateLocation(formats strfmt.Registry) error {
	if swag.IsZero(o.Location) { // not required
		return nil
	}

	if o.Location != nil {
		if err := o.Location.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "location")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "location")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this patch secret manager features body based on the context it is used
func (o *PatchSecretManagerFeaturesBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateLocation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PatchSecretManagerFeaturesBody) contextValidateLocation(ctx context.Context, formats strfmt.Registry) error {

	if o.Location != nil {

		if swag.IsZero(o.Location) { // not required
			return nil
		}

		if err := o.Location.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "location")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "location")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PatchSecretManagerFeaturesBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PatchSecretManagerFeaturesBody) UnmarshalBinary(b []byte) error {
	var res PatchSecretManagerFeaturesBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
PatchSecretManagerFeaturesParamsBodyLocation Location represents a target for an operation in HCP.
swagger:model PatchSecretManagerFeaturesParamsBodyLocation
*/
type PatchSecretManagerFeaturesParamsBodyLocation struct {

	// organization_id is the id of the organization.
	OrganizationID string `json:"organization_id,omitempty"`

	// region
	Region *models.LocationRegion `json:"region,omitempty"`
}

// Validate validates this patch secret manager features params body location
func (o *PatchSecretManagerFeaturesParamsBodyLocation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRegion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PatchSecretManagerFeaturesParamsBodyLocation) validateRegion(formats strfmt.Registry) error {
	if swag.IsZero(o.Region) { // not required
		return nil
	}

	if o.Region != nil {
		if err := o.Region.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "location" + "." + "region")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "location" + "." + "region")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this patch secret manager features params body location based on the context it is used
func (o *PatchSecretManagerFeaturesParamsBodyLocation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateRegion(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PatchSecretManagerFeaturesParamsBodyLocation) contextValidateRegion(ctx context.Context, formats strfmt.Registry) error {

	if o.Region != nil {

		if swag.IsZero(o.Region) { // not required
			return nil
		}

		if err := o.Region.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "location" + "." + "region")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "location" + "." + "region")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PatchSecretManagerFeaturesParamsBodyLocation) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PatchSecretManagerFeaturesParamsBodyLocation) UnmarshalBinary(b []byte) error {
	var res PatchSecretManagerFeaturesParamsBodyLocation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
