// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpCloudInfragraph20250507DomainAwsCloudWatchAlarm hashicorp cloud infragraph 20250507 domain aws cloud watch alarm
//
// swagger:model hashicorp.cloud.infragraph_20250507.domain.AwsCloudWatchAlarm
type HashicorpCloudInfragraph20250507DomainAwsCloudWatchAlarm struct {

	// actions enabled
	ActionsEnabled *bool `json:"actions_enabled,omitempty"`

	// alarm
	Alarm *HashicorpCloudInfragraph20250507DomainBaseAlarm `json:"alarm,omitempty"`

	// aws resource
	AwsResource *HashicorpCloudInfragraph20250507DomainAwsResource `json:"aws_resource,omitempty"`

	// comparison operator
	ComparisonOperator string `json:"comparison_operator,omitempty"`

	// datapoints to alarm
	DatapointsToAlarm *int32 `json:"datapoints_to_alarm,omitempty"`

	// evaluate low sample count percentile
	EvaluateLowSampleCountPercentile *string `json:"evaluate_low_sample_count_percentile,omitempty"`

	// evaluation periods
	EvaluationPeriods *int32 `json:"evaluation_periods,omitempty"`

	// extended statistic
	ExtendedStatistic *string `json:"extended_statistic,omitempty"`

	// metric name
	MetricName *string `json:"metric_name,omitempty"`

	// namespace
	Namespace *string `json:"namespace,omitempty"`

	// period
	Period *int32 `json:"period,omitempty"`

	// statistic
	Statistic *string `json:"statistic,omitempty"`

	// threshold
	Threshold *float32 `json:"threshold,omitempty"`

	// threshold metric id
	ThresholdMetricID *string `json:"threshold_metric_id,omitempty"`

	// treat missing data
	TreatMissingData *string `json:"treat_missing_data,omitempty"`

	// unit
	Unit *string `json:"unit,omitempty"`
}

// Validate validates this hashicorp cloud infragraph 20250507 domain aws cloud watch alarm
func (m *HashicorpCloudInfragraph20250507DomainAwsCloudWatchAlarm) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlarm(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAwsResource(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudInfragraph20250507DomainAwsCloudWatchAlarm) validateAlarm(formats strfmt.Registry) error {
	if swag.IsZero(m.Alarm) { // not required
		return nil
	}

	if m.Alarm != nil {
		if err := m.Alarm.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("alarm")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("alarm")
			}
			return err
		}
	}

	return nil
}

func (m *HashicorpCloudInfragraph20250507DomainAwsCloudWatchAlarm) validateAwsResource(formats strfmt.Registry) error {
	if swag.IsZero(m.AwsResource) { // not required
		return nil
	}

	if m.AwsResource != nil {
		if err := m.AwsResource.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("aws_resource")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("aws_resource")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this hashicorp cloud infragraph 20250507 domain aws cloud watch alarm based on the context it is used
func (m *HashicorpCloudInfragraph20250507DomainAwsCloudWatchAlarm) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAlarm(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAwsResource(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudInfragraph20250507DomainAwsCloudWatchAlarm) contextValidateAlarm(ctx context.Context, formats strfmt.Registry) error {

	if m.Alarm != nil {

		if swag.IsZero(m.Alarm) { // not required
			return nil
		}

		if err := m.Alarm.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("alarm")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("alarm")
			}
			return err
		}
	}

	return nil
}

func (m *HashicorpCloudInfragraph20250507DomainAwsCloudWatchAlarm) contextValidateAwsResource(ctx context.Context, formats strfmt.Registry) error {

	if m.AwsResource != nil {

		if swag.IsZero(m.AwsResource) { // not required
			return nil
		}

		if err := m.AwsResource.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("aws_resource")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("aws_resource")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudInfragraph20250507DomainAwsCloudWatchAlarm) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudInfragraph20250507DomainAwsCloudWatchAlarm) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudInfragraph20250507DomainAwsCloudWatchAlarm
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
