// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// HashicorpCloudInfragraph20250507LogicOperator LogicOperator is a type used to combine conditions using logical 'and' and 'or' operators.
//
// swagger:model hashicorp.cloud.infragraph_20250507.LogicOperator
type HashicorpCloudInfragraph20250507LogicOperator string

func NewHashicorpCloudInfragraph20250507LogicOperator(value HashicorpCloudInfragraph20250507LogicOperator) *HashicorpCloudInfragraph20250507LogicOperator {
	return &value
}

// Pointer returns a pointer to a freshly-allocated HashicorpCloudInfragraph20250507LogicOperator.
func (m HashicorpCloudInfragraph20250507LogicOperator) Pointer() *HashicorpCloudInfragraph20250507LogicOperator {
	return &m
}

const (

	// HashicorpCloudInfragraph20250507LogicOperatorLOGICOPERATORUNSPECIFIED captures enum value "LOGIC_OPERATOR_UNSPECIFIED"
	HashicorpCloudInfragraph20250507LogicOperatorLOGICOPERATORUNSPECIFIED HashicorpCloudInfragraph20250507LogicOperator = "LOGIC_OPERATOR_UNSPECIFIED"

	// HashicorpCloudInfragraph20250507LogicOperatorOR captures enum value "OR"
	HashicorpCloudInfragraph20250507LogicOperatorOR HashicorpCloudInfragraph20250507LogicOperator = "OR"

	// HashicorpCloudInfragraph20250507LogicOperatorAND captures enum value "AND"
	HashicorpCloudInfragraph20250507LogicOperatorAND HashicorpCloudInfragraph20250507LogicOperator = "AND"
)

// for schema
var hashicorpCloudInfragraph20250507LogicOperatorEnum []interface{}

func init() {
	var res []HashicorpCloudInfragraph20250507LogicOperator
	if err := json.Unmarshal([]byte(`["LOGIC_OPERATOR_UNSPECIFIED","OR","AND"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		hashicorpCloudInfragraph20250507LogicOperatorEnum = append(hashicorpCloudInfragraph20250507LogicOperatorEnum, v)
	}
}

func (m HashicorpCloudInfragraph20250507LogicOperator) validateHashicorpCloudInfragraph20250507LogicOperatorEnum(path, location string, value HashicorpCloudInfragraph20250507LogicOperator) error {
	if err := validate.EnumCase(path, location, value, hashicorpCloudInfragraph20250507LogicOperatorEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this hashicorp cloud infragraph 20250507 logic operator
func (m HashicorpCloudInfragraph20250507LogicOperator) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateHashicorpCloudInfragraph20250507LogicOperatorEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this hashicorp cloud infragraph 20250507 logic operator based on context it is used
func (m HashicorpCloudInfragraph20250507LogicOperator) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
