// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VaultRadar20230501EventUpdate EventUpdate represents an update to a single event's status.
//
// swagger:model vault_radar_20230501EventUpdate
type VaultRadar20230501EventUpdate struct {

	// event id
	EventID string `json:"event_id,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this vault radar 20230501 event update
func (m *VaultRadar20230501EventUpdate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this vault radar 20230501 event update based on context it is used
func (m *VaultRadar20230501EventUpdate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VaultRadar20230501EventUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VaultRadar20230501EventUpdate) UnmarshalBinary(b []byte) error {
	var res VaultRadar20230501EventUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
