// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpCloudResourcemanagerConstraint Constraint has the information about the policy constraints
//
// swagger:model hashicorp.cloud.resourcemanager.Constraint
type HashicorpCloudResourcemanagerConstraint struct {

	// DeniedPermissions is the list of denied permissions.
	DeniedPermissions []string `json:"denied_permissions"`

	// Description is friendly description for this constraint.
	Description string `json:"description,omitempty"`

	// Id is defined by services when registered. Validated for format "constraints/service.name".
	ID string `json:"id,omitempty"`

	// Service is the name of the service that constraint belongs to .
	Service string `json:"service,omitempty"`

	// Title is friendly name for this constraint.
	Title string `json:"title,omitempty"`
}

// Validate validates this hashicorp cloud resourcemanager constraint
func (m *HashicorpCloudResourcemanagerConstraint) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud resourcemanager constraint based on context it is used
func (m *HashicorpCloudResourcemanagerConstraint) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerConstraint) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerConstraint) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudResourcemanagerConstraint
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
