// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpCloudWebhookWebhookConfig The webhook configuration used to deliver event payloads.
//
// swagger:model hashicorp.cloud.webhook.WebhookConfig
type HashicorpCloudWebhookWebhookConfig struct {

	// The optional HMAC key used to sign all requests.
	HmacKey string `json:"hmac_key,omitempty"`

	// The HTTP or HTTPS endpoint URL that HCP Packer delivers the requests to.
	URL string `json:"url,omitempty"`
}

// Validate validates this hashicorp cloud webhook webhook config
func (m *HashicorpCloudWebhookWebhookConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud webhook webhook config based on context it is used
func (m *HashicorpCloudWebhookWebhookConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudWebhookWebhookConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudWebhookWebhookConfig) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudWebhookWebhookConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
