// Code generated by go-swagger; DO NOT EDIT.

package work_item_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewWorkItemServiceGetWorkItemParams creates a new WorkItemServiceGetWorkItemParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewWorkItemServiceGetWorkItemParams() *WorkItemServiceGetWorkItemParams {
	return &WorkItemServiceGetWorkItemParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewWorkItemServiceGetWorkItemParamsWithTimeout creates a new WorkItemServiceGetWorkItemParams object
// with the ability to set a timeout on a request.
func NewWorkItemServiceGetWorkItemParamsWithTimeout(timeout time.Duration) *WorkItemServiceGetWorkItemParams {
	return &WorkItemServiceGetWorkItemParams{
		timeout: timeout,
	}
}

// NewWorkItemServiceGetWorkItemParamsWithContext creates a new WorkItemServiceGetWorkItemParams object
// with the ability to set a context for a request.
func NewWorkItemServiceGetWorkItemParamsWithContext(ctx context.Context) *WorkItemServiceGetWorkItemParams {
	return &WorkItemServiceGetWorkItemParams{
		Context: ctx,
	}
}

// NewWorkItemServiceGetWorkItemParamsWithHTTPClient creates a new WorkItemServiceGetWorkItemParams object
// with the ability to set a custom HTTPClient for a request.
func NewWorkItemServiceGetWorkItemParamsWithHTTPClient(client *http.Client) *WorkItemServiceGetWorkItemParams {
	return &WorkItemServiceGetWorkItemParams{
		HTTPClient: client,
	}
}

/*
WorkItemServiceGetWorkItemParams contains all the parameters to send to the API endpoint

	for the work item service get work item operation.

	Typically these are written to a http.Request.
*/
type WorkItemServiceGetWorkItemParams struct {

	// WorkItemID.
	WorkItemID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the work item service get work item params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WorkItemServiceGetWorkItemParams) WithDefaults() *WorkItemServiceGetWorkItemParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the work item service get work item params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WorkItemServiceGetWorkItemParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the work item service get work item params
func (o *WorkItemServiceGetWorkItemParams) WithTimeout(timeout time.Duration) *WorkItemServiceGetWorkItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the work item service get work item params
func (o *WorkItemServiceGetWorkItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the work item service get work item params
func (o *WorkItemServiceGetWorkItemParams) WithContext(ctx context.Context) *WorkItemServiceGetWorkItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the work item service get work item params
func (o *WorkItemServiceGetWorkItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the work item service get work item params
func (o *WorkItemServiceGetWorkItemParams) WithHTTPClient(client *http.Client) *WorkItemServiceGetWorkItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the work item service get work item params
func (o *WorkItemServiceGetWorkItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWorkItemID adds the workItemID to the work item service get work item params
func (o *WorkItemServiceGetWorkItemParams) WithWorkItemID(workItemID string) *WorkItemServiceGetWorkItemParams {
	o.SetWorkItemID(workItemID)
	return o
}

// SetWorkItemID adds the workItemId to the work item service get work item params
func (o *WorkItemServiceGetWorkItemParams) SetWorkItemID(workItemID string) {
	o.WorkItemID = workItemID
}

// WriteToRequest writes these params to a swagger request
func (o *WorkItemServiceGetWorkItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param work_item_id
	if err := r.SetPathParam("work_item_id", o.WorkItemID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
