// Code generated by go-swagger; DO NOT EDIT.

package network_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hashicorp/hcp-sdk-go/clients/cloud-network/stable/2020-09-07/models"
	cloud "github.com/hashicorp/hcp-sdk-go/clients/cloud-shared/v1/models"
)

// CreatePrivateLinkServiceReader is a Reader for the CreatePrivateLinkService structure.
type CreatePrivateLinkServiceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreatePrivateLinkServiceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreatePrivateLinkServiceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreatePrivateLinkServiceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreatePrivateLinkServiceOK creates a CreatePrivateLinkServiceOK with default headers values
func NewCreatePrivateLinkServiceOK() *CreatePrivateLinkServiceOK {
	return &CreatePrivateLinkServiceOK{}
}

/*
CreatePrivateLinkServiceOK describes a response with status code 200, with default header values.

A successful response.
*/
type CreatePrivateLinkServiceOK struct {
	Payload *models.HashicorpCloudNetwork20200907CreatePrivateLinkServiceResponse
}

// IsSuccess returns true when this create private link service o k response has a 2xx status code
func (o *CreatePrivateLinkServiceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create private link service o k response has a 3xx status code
func (o *CreatePrivateLinkServiceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create private link service o k response has a 4xx status code
func (o *CreatePrivateLinkServiceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create private link service o k response has a 5xx status code
func (o *CreatePrivateLinkServiceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create private link service o k response a status code equal to that given
func (o *CreatePrivateLinkServiceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create private link service o k response
func (o *CreatePrivateLinkServiceOK) Code() int {
	return 200
}

func (o *CreatePrivateLinkServiceOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /network/2020-09-07/organizations/{private_link_service.hvn.location.organization_id}/projects/{private_link_service.hvn.location.project_id}/networks/{private_link_service.hvn.id}/private-link-services][%d] createPrivateLinkServiceOK %s", 200, payload)
}

func (o *CreatePrivateLinkServiceOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /network/2020-09-07/organizations/{private_link_service.hvn.location.organization_id}/projects/{private_link_service.hvn.location.project_id}/networks/{private_link_service.hvn.id}/private-link-services][%d] createPrivateLinkServiceOK %s", 200, payload)
}

func (o *CreatePrivateLinkServiceOK) GetPayload() *models.HashicorpCloudNetwork20200907CreatePrivateLinkServiceResponse {
	return o.Payload
}

func (o *CreatePrivateLinkServiceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HashicorpCloudNetwork20200907CreatePrivateLinkServiceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePrivateLinkServiceDefault creates a CreatePrivateLinkServiceDefault with default headers values
func NewCreatePrivateLinkServiceDefault(code int) *CreatePrivateLinkServiceDefault {
	return &CreatePrivateLinkServiceDefault{
		_statusCode: code,
	}
}

/*
CreatePrivateLinkServiceDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type CreatePrivateLinkServiceDefault struct {
	_statusCode int

	Payload *cloud.GrpcGatewayRuntimeError
}

// IsSuccess returns true when this create private link service default response has a 2xx status code
func (o *CreatePrivateLinkServiceDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this create private link service default response has a 3xx status code
func (o *CreatePrivateLinkServiceDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this create private link service default response has a 4xx status code
func (o *CreatePrivateLinkServiceDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this create private link service default response has a 5xx status code
func (o *CreatePrivateLinkServiceDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this create private link service default response a status code equal to that given
func (o *CreatePrivateLinkServiceDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the create private link service default response
func (o *CreatePrivateLinkServiceDefault) Code() int {
	return o._statusCode
}

func (o *CreatePrivateLinkServiceDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /network/2020-09-07/organizations/{private_link_service.hvn.location.organization_id}/projects/{private_link_service.hvn.location.project_id}/networks/{private_link_service.hvn.id}/private-link-services][%d] CreatePrivateLinkService default %s", o._statusCode, payload)
}

func (o *CreatePrivateLinkServiceDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /network/2020-09-07/organizations/{private_link_service.hvn.location.organization_id}/projects/{private_link_service.hvn.location.project_id}/networks/{private_link_service.hvn.id}/private-link-services][%d] CreatePrivateLinkService default %s", o._statusCode, payload)
}

func (o *CreatePrivateLinkServiceDefault) GetPayload() *cloud.GrpcGatewayRuntimeError {
	return o.Payload
}

func (o *CreatePrivateLinkServiceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(cloud.GrpcGatewayRuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
