// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// HashicorpCloudPackerDeleteBucketResponse hashicorp cloud packer delete bucket response
//
// swagger:model hashicorp.cloud.packer.DeleteBucketResponse
type HashicorpCloudPackerDeleteBucketResponse interface{}
