// Code generated by go-swagger; DO NOT EDIT.

package invitations_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hashicorp/hcp-sdk-go/clients/cloud-iam/stable/2019-12-10/models"
)

// NewAcceptOrganizationInvitationParams creates a new AcceptOrganizationInvitationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAcceptOrganizationInvitationParams() *AcceptOrganizationInvitationParams {
	return &AcceptOrganizationInvitationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAcceptOrganizationInvitationParamsWithTimeout creates a new AcceptOrganizationInvitationParams object
// with the ability to set a timeout on a request.
func NewAcceptOrganizationInvitationParamsWithTimeout(timeout time.Duration) *AcceptOrganizationInvitationParams {
	return &AcceptOrganizationInvitationParams{
		timeout: timeout,
	}
}

// NewAcceptOrganizationInvitationParamsWithContext creates a new AcceptOrganizationInvitationParams object
// with the ability to set a context for a request.
func NewAcceptOrganizationInvitationParamsWithContext(ctx context.Context) *AcceptOrganizationInvitationParams {
	return &AcceptOrganizationInvitationParams{
		Context: ctx,
	}
}

// NewAcceptOrganizationInvitationParamsWithHTTPClient creates a new AcceptOrganizationInvitationParams object
// with the ability to set a custom HTTPClient for a request.
func NewAcceptOrganizationInvitationParamsWithHTTPClient(client *http.Client) *AcceptOrganizationInvitationParams {
	return &AcceptOrganizationInvitationParams{
		HTTPClient: client,
	}
}

/*
AcceptOrganizationInvitationParams contains all the parameters to send to the API endpoint

	for the accept organization invitation operation.

	Typically these are written to a http.Request.
*/
type AcceptOrganizationInvitationParams struct {

	// Body.
	Body *models.HashicorpCloudIamAcceptOrganizationInvitationRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the accept organization invitation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AcceptOrganizationInvitationParams) WithDefaults() *AcceptOrganizationInvitationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the accept organization invitation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AcceptOrganizationInvitationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the accept organization invitation params
func (o *AcceptOrganizationInvitationParams) WithTimeout(timeout time.Duration) *AcceptOrganizationInvitationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the accept organization invitation params
func (o *AcceptOrganizationInvitationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the accept organization invitation params
func (o *AcceptOrganizationInvitationParams) WithContext(ctx context.Context) *AcceptOrganizationInvitationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the accept organization invitation params
func (o *AcceptOrganizationInvitationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the accept organization invitation params
func (o *AcceptOrganizationInvitationParams) WithHTTPClient(client *http.Client) *AcceptOrganizationInvitationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the accept organization invitation params
func (o *AcceptOrganizationInvitationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the accept organization invitation params
func (o *AcceptOrganizationInvitationParams) WithBody(body *models.HashicorpCloudIamAcceptOrganizationInvitationRequest) *AcceptOrganizationInvitationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the accept organization invitation params
func (o *AcceptOrganizationInvitationParams) SetBody(body *models.HashicorpCloudIamAcceptOrganizationInvitationRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AcceptOrganizationInvitationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
