// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpCloudConsul20210204CidrRange CidrRange specifies an IP address and prefix in CIDR format.
//
// swagger:model hashicorp.cloud.consul_20210204.CidrRange
type HashicorpCloudConsul20210204CidrRange struct {

	// The IPv4 or IPv6 address range including prefix.
	// E.g. 172.25.16.0/24 or 2001:d00::/24
	Address string `json:"address,omitempty"`

	// An optional description of the IP address range.
	Description string `json:"description,omitempty"`
}

// Validate validates this hashicorp cloud consul 20210204 cidr range
func (m *HashicorpCloudConsul20210204CidrRange) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud consul 20210204 cidr range based on context it is used
func (m *HashicorpCloudConsul20210204CidrRange) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsul20210204CidrRange) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsul20210204CidrRange) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsul20210204CidrRange
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
