// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Secrets20231128AssumeRoleResponse secrets 20231128 assume role response
//
// swagger:model secrets_20231128AssumeRoleResponse
type Secrets20231128AssumeRoleResponse struct {

	// role arn
	RoleArn string `json:"role_arn,omitempty"`
}

// Validate validates this secrets 20231128 assume role response
func (m *Secrets20231128AssumeRoleResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this secrets 20231128 assume role response based on context it is used
func (m *Secrets20231128AssumeRoleResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Secrets20231128AssumeRoleResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Secrets20231128AssumeRoleResponse) UnmarshalBinary(b []byte) error {
	var res Secrets20231128AssumeRoleResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
