// Code generated by go-swagger; DO NOT EDIT.

package terraform_cloud_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	cloud "github.com/hashicorp/hcp-sdk-go/clients/cloud-shared/v1/models"
	"github.com/hashicorp/hcp-sdk-go/clients/cloud-waypoint-service/preview/2022-02-03/models"
)

// TerraformCloudConfigUpdateTFCConfigReader is a Reader for the TerraformCloudConfigUpdateTFCConfig structure.
type TerraformCloudConfigUpdateTFCConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TerraformCloudConfigUpdateTFCConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTerraformCloudConfigUpdateTFCConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewTerraformCloudConfigUpdateTFCConfigDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewTerraformCloudConfigUpdateTFCConfigOK creates a TerraformCloudConfigUpdateTFCConfigOK with default headers values
func NewTerraformCloudConfigUpdateTFCConfigOK() *TerraformCloudConfigUpdateTFCConfigOK {
	return &TerraformCloudConfigUpdateTFCConfigOK{}
}

/*
TerraformCloudConfigUpdateTFCConfigOK describes a response with status code 200, with default header values.

A successful response.
*/
type TerraformCloudConfigUpdateTFCConfigOK struct {
	Payload *models.HashicorpCloudWaypointUpdateTFCConfigResponse
}

// IsSuccess returns true when this terraform cloud config update t f c config o k response has a 2xx status code
func (o *TerraformCloudConfigUpdateTFCConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this terraform cloud config update t f c config o k response has a 3xx status code
func (o *TerraformCloudConfigUpdateTFCConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this terraform cloud config update t f c config o k response has a 4xx status code
func (o *TerraformCloudConfigUpdateTFCConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this terraform cloud config update t f c config o k response has a 5xx status code
func (o *TerraformCloudConfigUpdateTFCConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this terraform cloud config update t f c config o k response a status code equal to that given
func (o *TerraformCloudConfigUpdateTFCConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the terraform cloud config update t f c config o k response
func (o *TerraformCloudConfigUpdateTFCConfigOK) Code() int {
	return 200
}

func (o *TerraformCloudConfigUpdateTFCConfigOK) Error() string {
	return fmt.Sprintf("[PATCH /waypoint/2022-02-03/namespace/{namespace_id}/tfcconfig][%d] terraformCloudConfigUpdateTFCConfigOK  %+v", 200, o.Payload)
}

func (o *TerraformCloudConfigUpdateTFCConfigOK) String() string {
	return fmt.Sprintf("[PATCH /waypoint/2022-02-03/namespace/{namespace_id}/tfcconfig][%d] terraformCloudConfigUpdateTFCConfigOK  %+v", 200, o.Payload)
}

func (o *TerraformCloudConfigUpdateTFCConfigOK) GetPayload() *models.HashicorpCloudWaypointUpdateTFCConfigResponse {
	return o.Payload
}

func (o *TerraformCloudConfigUpdateTFCConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HashicorpCloudWaypointUpdateTFCConfigResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTerraformCloudConfigUpdateTFCConfigDefault creates a TerraformCloudConfigUpdateTFCConfigDefault with default headers values
func NewTerraformCloudConfigUpdateTFCConfigDefault(code int) *TerraformCloudConfigUpdateTFCConfigDefault {
	return &TerraformCloudConfigUpdateTFCConfigDefault{
		_statusCode: code,
	}
}

/*
TerraformCloudConfigUpdateTFCConfigDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type TerraformCloudConfigUpdateTFCConfigDefault struct {
	_statusCode int

	Payload *cloud.GrpcGatewayRuntimeError
}

// IsSuccess returns true when this terraform cloud config update t f c config default response has a 2xx status code
func (o *TerraformCloudConfigUpdateTFCConfigDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this terraform cloud config update t f c config default response has a 3xx status code
func (o *TerraformCloudConfigUpdateTFCConfigDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this terraform cloud config update t f c config default response has a 4xx status code
func (o *TerraformCloudConfigUpdateTFCConfigDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this terraform cloud config update t f c config default response has a 5xx status code
func (o *TerraformCloudConfigUpdateTFCConfigDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this terraform cloud config update t f c config default response a status code equal to that given
func (o *TerraformCloudConfigUpdateTFCConfigDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the terraform cloud config update t f c config default response
func (o *TerraformCloudConfigUpdateTFCConfigDefault) Code() int {
	return o._statusCode
}

func (o *TerraformCloudConfigUpdateTFCConfigDefault) Error() string {
	return fmt.Sprintf("[PATCH /waypoint/2022-02-03/namespace/{namespace_id}/tfcconfig][%d] TerraformCloudConfig_UpdateTFCConfig default  %+v", o._statusCode, o.Payload)
}

func (o *TerraformCloudConfigUpdateTFCConfigDefault) String() string {
	return fmt.Sprintf("[PATCH /waypoint/2022-02-03/namespace/{namespace_id}/tfcconfig][%d] TerraformCloudConfig_UpdateTFCConfig default  %+v", o._statusCode, o.Payload)
}

func (o *TerraformCloudConfigUpdateTFCConfigDefault) GetPayload() *cloud.GrpcGatewayRuntimeError {
	return o.Payload
}

func (o *TerraformCloudConfigUpdateTFCConfigDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(cloud.GrpcGatewayRuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
