// Code generated by go-swagger; DO NOT EDIT.

package invoice_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new invoice service API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for invoice service API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	InvoiceServiceGetUsage(params *InvoiceServiceGetUsageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*InvoiceServiceGetUsageOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
InvoiceServiceGetUsage gets usage returns the current billing period s usage usage information is not calculated on demand but the response explicitly specifies the considered billing period
*/
func (a *Client) InvoiceServiceGetUsage(params *InvoiceServiceGetUsageParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*InvoiceServiceGetUsageOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewInvoiceServiceGetUsageParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "InvoiceService_GetUsage",
		Method:             "GET",
		PathPattern:        "/billing/2020-11-05/organizations/{organization_id}/accounts/{billing_account_id}/usage",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &InvoiceServiceGetUsageReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*InvoiceServiceGetUsageOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*InvoiceServiceGetUsageDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
