// Code generated by go-swagger; DO NOT EDIT.

package version_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hashicorp/hcp-sdk-go/clients/cloud-vagrant-box-registry/preview/2022-09-30/models"
)

// ReadVersionReader is a Reader for the ReadVersion structure.
type ReadVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReadVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewReadVersionOK creates a ReadVersionOK with default headers values
func NewReadVersionOK() *ReadVersionOK {
	return &ReadVersionOK{}
}

/*
ReadVersionOK describes a response with status code 200, with default header values.

A successful response.
*/
type ReadVersionOK struct {
	Payload *models.HashicorpCloudVagrantReadVersionResponse
}

// IsSuccess returns true when this read version o k response has a 2xx status code
func (o *ReadVersionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this read version o k response has a 3xx status code
func (o *ReadVersionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this read version o k response has a 4xx status code
func (o *ReadVersionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this read version o k response has a 5xx status code
func (o *ReadVersionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this read version o k response a status code equal to that given
func (o *ReadVersionOK) IsCode(code int) bool {
	return code == 200
}

func (o *ReadVersionOK) Error() string {
	return fmt.Sprintf("[GET /vagrant/2022-09-30/registry/{registry}/boxes/{box}/versions/{version}][%d] readVersionOK  %+v", 200, o.Payload)
}

func (o *ReadVersionOK) String() string {
	return fmt.Sprintf("[GET /vagrant/2022-09-30/registry/{registry}/boxes/{box}/versions/{version}][%d] readVersionOK  %+v", 200, o.Payload)
}

func (o *ReadVersionOK) GetPayload() *models.HashicorpCloudVagrantReadVersionResponse {
	return o.Payload
}

func (o *ReadVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HashicorpCloudVagrantReadVersionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
