// Code generated by go-swagger; DO NOT EDIT.

package packer_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hashicorp/hcp-sdk-go/clients/cloud-packer-service/stable/2023-01-01/models"
)

// NewPackerServiceUpdateEnforcedBlockParams creates a new PackerServiceUpdateEnforcedBlockParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPackerServiceUpdateEnforcedBlockParams() *PackerServiceUpdateEnforcedBlockParams {
	return &PackerServiceUpdateEnforcedBlockParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPackerServiceUpdateEnforcedBlockParamsWithTimeout creates a new PackerServiceUpdateEnforcedBlockParams object
// with the ability to set a timeout on a request.
func NewPackerServiceUpdateEnforcedBlockParamsWithTimeout(timeout time.Duration) *PackerServiceUpdateEnforcedBlockParams {
	return &PackerServiceUpdateEnforcedBlockParams{
		timeout: timeout,
	}
}

// NewPackerServiceUpdateEnforcedBlockParamsWithContext creates a new PackerServiceUpdateEnforcedBlockParams object
// with the ability to set a context for a request.
func NewPackerServiceUpdateEnforcedBlockParamsWithContext(ctx context.Context) *PackerServiceUpdateEnforcedBlockParams {
	return &PackerServiceUpdateEnforcedBlockParams{
		Context: ctx,
	}
}

// NewPackerServiceUpdateEnforcedBlockParamsWithHTTPClient creates a new PackerServiceUpdateEnforcedBlockParams object
// with the ability to set a custom HTTPClient for a request.
func NewPackerServiceUpdateEnforcedBlockParamsWithHTTPClient(client *http.Client) *PackerServiceUpdateEnforcedBlockParams {
	return &PackerServiceUpdateEnforcedBlockParams{
		HTTPClient: client,
	}
}

/*
PackerServiceUpdateEnforcedBlockParams contains all the parameters to send to the API endpoint

	for the packer service update enforced block operation.

	Typically these are written to a http.Request.
*/
type PackerServiceUpdateEnforcedBlockParams struct {

	// Body.
	Body *models.HashicorpCloudPacker20230101UpdateEnforcedBlockBody

	// EnforcedBlockID.
	EnforcedBlockID string

	/* LocationOrganizationID.

	   organization_id is the id of the organization.
	*/
	LocationOrganizationID string

	/* LocationProjectID.

	   project_id is the projects id.
	*/
	LocationProjectID string

	/* LocationRegionProvider.

	   unused HCP platform field, HCP Packer does not support the region argument
	*/
	LocationRegionProvider *string

	/* LocationRegionRegion.

	   unused HCP platform field, HCP Packer does not support the region argument
	*/
	LocationRegionRegion *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the packer service update enforced block params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PackerServiceUpdateEnforcedBlockParams) WithDefaults() *PackerServiceUpdateEnforcedBlockParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the packer service update enforced block params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PackerServiceUpdateEnforcedBlockParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the packer service update enforced block params
func (o *PackerServiceUpdateEnforcedBlockParams) WithTimeout(timeout time.Duration) *PackerServiceUpdateEnforcedBlockParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the packer service update enforced block params
func (o *PackerServiceUpdateEnforcedBlockParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the packer service update enforced block params
func (o *PackerServiceUpdateEnforcedBlockParams) WithContext(ctx context.Context) *PackerServiceUpdateEnforcedBlockParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the packer service update enforced block params
func (o *PackerServiceUpdateEnforcedBlockParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the packer service update enforced block params
func (o *PackerServiceUpdateEnforcedBlockParams) WithHTTPClient(client *http.Client) *PackerServiceUpdateEnforcedBlockParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the packer service update enforced block params
func (o *PackerServiceUpdateEnforcedBlockParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the packer service update enforced block params
func (o *PackerServiceUpdateEnforcedBlockParams) WithBody(body *models.HashicorpCloudPacker20230101UpdateEnforcedBlockBody) *PackerServiceUpdateEnforcedBlockParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the packer service update enforced block params
func (o *PackerServiceUpdateEnforcedBlockParams) SetBody(body *models.HashicorpCloudPacker20230101UpdateEnforcedBlockBody) {
	o.Body = body
}

// WithEnforcedBlockID adds the enforcedBlockID to the packer service update enforced block params
func (o *PackerServiceUpdateEnforcedBlockParams) WithEnforcedBlockID(enforcedBlockID string) *PackerServiceUpdateEnforcedBlockParams {
	o.SetEnforcedBlockID(enforcedBlockID)
	return o
}

// SetEnforcedBlockID adds the enforcedBlockId to the packer service update enforced block params
func (o *PackerServiceUpdateEnforcedBlockParams) SetEnforcedBlockID(enforcedBlockID string) {
	o.EnforcedBlockID = enforcedBlockID
}

// WithLocationOrganizationID adds the locationOrganizationID to the packer service update enforced block params
func (o *PackerServiceUpdateEnforcedBlockParams) WithLocationOrganizationID(locationOrganizationID string) *PackerServiceUpdateEnforcedBlockParams {
	o.SetLocationOrganizationID(locationOrganizationID)
	return o
}

// SetLocationOrganizationID adds the locationOrganizationId to the packer service update enforced block params
func (o *PackerServiceUpdateEnforcedBlockParams) SetLocationOrganizationID(locationOrganizationID string) {
	o.LocationOrganizationID = locationOrganizationID
}

// WithLocationProjectID adds the locationProjectID to the packer service update enforced block params
func (o *PackerServiceUpdateEnforcedBlockParams) WithLocationProjectID(locationProjectID string) *PackerServiceUpdateEnforcedBlockParams {
	o.SetLocationProjectID(locationProjectID)
	return o
}

// SetLocationProjectID adds the locationProjectId to the packer service update enforced block params
func (o *PackerServiceUpdateEnforcedBlockParams) SetLocationProjectID(locationProjectID string) {
	o.LocationProjectID = locationProjectID
}

// WithLocationRegionProvider adds the locationRegionProvider to the packer service update enforced block params
func (o *PackerServiceUpdateEnforcedBlockParams) WithLocationRegionProvider(locationRegionProvider *string) *PackerServiceUpdateEnforcedBlockParams {
	o.SetLocationRegionProvider(locationRegionProvider)
	return o
}

// SetLocationRegionProvider adds the locationRegionProvider to the packer service update enforced block params
func (o *PackerServiceUpdateEnforcedBlockParams) SetLocationRegionProvider(locationRegionProvider *string) {
	o.LocationRegionProvider = locationRegionProvider
}

// WithLocationRegionRegion adds the locationRegionRegion to the packer service update enforced block params
func (o *PackerServiceUpdateEnforcedBlockParams) WithLocationRegionRegion(locationRegionRegion *string) *PackerServiceUpdateEnforcedBlockParams {
	o.SetLocationRegionRegion(locationRegionRegion)
	return o
}

// SetLocationRegionRegion adds the locationRegionRegion to the packer service update enforced block params
func (o *PackerServiceUpdateEnforcedBlockParams) SetLocationRegionRegion(locationRegionRegion *string) {
	o.LocationRegionRegion = locationRegionRegion
}

// WriteToRequest writes these params to a swagger request
func (o *PackerServiceUpdateEnforcedBlockParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param enforced_block_id
	if err := r.SetPathParam("enforced_block_id", o.EnforcedBlockID); err != nil {
		return err
	}

	// path param location.organization_id
	if err := r.SetPathParam("location.organization_id", o.LocationOrganizationID); err != nil {
		return err
	}

	// path param location.project_id
	if err := r.SetPathParam("location.project_id", o.LocationProjectID); err != nil {
		return err
	}

	if o.LocationRegionProvider != nil {

		// query param location.region.provider
		var qrLocationRegionProvider string

		if o.LocationRegionProvider != nil {
			qrLocationRegionProvider = *o.LocationRegionProvider
		}
		qLocationRegionProvider := qrLocationRegionProvider
		if qLocationRegionProvider != "" {

			if err := r.SetQueryParam("location.region.provider", qLocationRegionProvider); err != nil {
				return err
			}
		}
	}

	if o.LocationRegionRegion != nil {

		// query param location.region.region
		var qrLocationRegionRegion string

		if o.LocationRegionRegion != nil {
			qrLocationRegionRegion = *o.LocationRegionRegion
		}
		qLocationRegionRegion := qrLocationRegionRegion
		if qLocationRegionRegion != "" {

			if err := r.SetQueryParam("location.region.region", qLocationRegionRegion); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
