// Code generated by go-swagger; DO NOT EDIT.

package activation_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hashicorp/hcp-sdk-go/clients/cloud-infragraph/stable/2025-05-07/models"
	cloud "github.com/hashicorp/hcp-sdk-go/clients/cloud-shared/v1/models"
)

// ActivationServiceGetCustomerReader is a Reader for the ActivationServiceGetCustomer structure.
type ActivationServiceGetCustomerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ActivationServiceGetCustomerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewActivationServiceGetCustomerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewActivationServiceGetCustomerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewActivationServiceGetCustomerOK creates a ActivationServiceGetCustomerOK with default headers values
func NewActivationServiceGetCustomerOK() *ActivationServiceGetCustomerOK {
	return &ActivationServiceGetCustomerOK{}
}

/*
ActivationServiceGetCustomerOK describes a response with status code 200, with default header values.

A successful response.
*/
type ActivationServiceGetCustomerOK struct {
	Payload *models.HashicorpCloudInfragraph20250507GetCustomerResponse
}

// IsSuccess returns true when this activation service get customer o k response has a 2xx status code
func (o *ActivationServiceGetCustomerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this activation service get customer o k response has a 3xx status code
func (o *ActivationServiceGetCustomerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this activation service get customer o k response has a 4xx status code
func (o *ActivationServiceGetCustomerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this activation service get customer o k response has a 5xx status code
func (o *ActivationServiceGetCustomerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this activation service get customer o k response a status code equal to that given
func (o *ActivationServiceGetCustomerOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the activation service get customer o k response
func (o *ActivationServiceGetCustomerOK) Code() int {
	return 200
}

func (o *ActivationServiceGetCustomerOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /infragraph/2025-05-07/organizations/{location.organization_id}/customer][%d] activationServiceGetCustomerOK %s", 200, payload)
}

func (o *ActivationServiceGetCustomerOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /infragraph/2025-05-07/organizations/{location.organization_id}/customer][%d] activationServiceGetCustomerOK %s", 200, payload)
}

func (o *ActivationServiceGetCustomerOK) GetPayload() *models.HashicorpCloudInfragraph20250507GetCustomerResponse {
	return o.Payload
}

func (o *ActivationServiceGetCustomerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HashicorpCloudInfragraph20250507GetCustomerResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewActivationServiceGetCustomerDefault creates a ActivationServiceGetCustomerDefault with default headers values
func NewActivationServiceGetCustomerDefault(code int) *ActivationServiceGetCustomerDefault {
	return &ActivationServiceGetCustomerDefault{
		_statusCode: code,
	}
}

/*
ActivationServiceGetCustomerDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ActivationServiceGetCustomerDefault struct {
	_statusCode int

	Payload *cloud.GoogleRPCStatus
}

// IsSuccess returns true when this activation service get customer default response has a 2xx status code
func (o *ActivationServiceGetCustomerDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this activation service get customer default response has a 3xx status code
func (o *ActivationServiceGetCustomerDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this activation service get customer default response has a 4xx status code
func (o *ActivationServiceGetCustomerDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this activation service get customer default response has a 5xx status code
func (o *ActivationServiceGetCustomerDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this activation service get customer default response a status code equal to that given
func (o *ActivationServiceGetCustomerDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the activation service get customer default response
func (o *ActivationServiceGetCustomerDefault) Code() int {
	return o._statusCode
}

func (o *ActivationServiceGetCustomerDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /infragraph/2025-05-07/organizations/{location.organization_id}/customer][%d] ActivationService_GetCustomer default %s", o._statusCode, payload)
}

func (o *ActivationServiceGetCustomerDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /infragraph/2025-05-07/organizations/{location.organization_id}/customer][%d] ActivationService_GetCustomer default %s", o._statusCode, payload)
}

func (o *ActivationServiceGetCustomerDefault) GetPayload() *cloud.GoogleRPCStatus {
	return o.Payload
}

func (o *ActivationServiceGetCustomerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(cloud.GoogleRPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
