// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpWaypointCreateProjectTemplateResponse hashicorp waypoint create project template response
//
// swagger:model hashicorp.waypoint.CreateProjectTemplateResponse
type HashicorpWaypointCreateProjectTemplateResponse struct {

	// project template
	ProjectTemplate *HashicorpWaypointProjectTemplate `json:"project_template,omitempty"`
}

// Validate validates this hashicorp waypoint create project template response
func (m *HashicorpWaypointCreateProjectTemplateResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProjectTemplate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpWaypointCreateProjectTemplateResponse) validateProjectTemplate(formats strfmt.Registry) error {
	if swag.IsZero(m.ProjectTemplate) { // not required
		return nil
	}

	if m.ProjectTemplate != nil {
		if err := m.ProjectTemplate.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("project_template")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("project_template")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this hashicorp waypoint create project template response based on the context it is used
func (m *HashicorpWaypointCreateProjectTemplateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateProjectTemplate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpWaypointCreateProjectTemplateResponse) contextValidateProjectTemplate(ctx context.Context, formats strfmt.Registry) error {

	if m.ProjectTemplate != nil {

		if swag.IsZero(m.ProjectTemplate) { // not required
			return nil
		}

		if err := m.ProjectTemplate.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("project_template")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("project_template")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpWaypointCreateProjectTemplateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpWaypointCreateProjectTemplateResponse) UnmarshalBinary(b []byte) error {
	var res HashicorpWaypointCreateProjectTemplateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
