// Code generated by go-swagger; DO NOT EDIT.

package waypoint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewWaypointGetAddOnDefinitionParams creates a new WaypointGetAddOnDefinitionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewWaypointGetAddOnDefinitionParams() *WaypointGetAddOnDefinitionParams {
	return &WaypointGetAddOnDefinitionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewWaypointGetAddOnDefinitionParamsWithTimeout creates a new WaypointGetAddOnDefinitionParams object
// with the ability to set a timeout on a request.
func NewWaypointGetAddOnDefinitionParamsWithTimeout(timeout time.Duration) *WaypointGetAddOnDefinitionParams {
	return &WaypointGetAddOnDefinitionParams{
		timeout: timeout,
	}
}

// NewWaypointGetAddOnDefinitionParamsWithContext creates a new WaypointGetAddOnDefinitionParams object
// with the ability to set a context for a request.
func NewWaypointGetAddOnDefinitionParamsWithContext(ctx context.Context) *WaypointGetAddOnDefinitionParams {
	return &WaypointGetAddOnDefinitionParams{
		Context: ctx,
	}
}

// NewWaypointGetAddOnDefinitionParamsWithHTTPClient creates a new WaypointGetAddOnDefinitionParams object
// with the ability to set a custom HTTPClient for a request.
func NewWaypointGetAddOnDefinitionParamsWithHTTPClient(client *http.Client) *WaypointGetAddOnDefinitionParams {
	return &WaypointGetAddOnDefinitionParams{
		HTTPClient: client,
	}
}

/*
WaypointGetAddOnDefinitionParams contains all the parameters to send to the API endpoint

	for the waypoint get add on definition operation.

	Typically these are written to a http.Request.
*/
type WaypointGetAddOnDefinitionParams struct {

	// AddOnDefinitionID.
	AddOnDefinitionID string

	// AddOnDefinitionName.
	AddOnDefinitionName *string

	/* NamespaceID.

	   namespace_id is the id of the namespace.
	*/
	NamespaceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the waypoint get add on definition params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WaypointGetAddOnDefinitionParams) WithDefaults() *WaypointGetAddOnDefinitionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the waypoint get add on definition params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WaypointGetAddOnDefinitionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the waypoint get add on definition params
func (o *WaypointGetAddOnDefinitionParams) WithTimeout(timeout time.Duration) *WaypointGetAddOnDefinitionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the waypoint get add on definition params
func (o *WaypointGetAddOnDefinitionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the waypoint get add on definition params
func (o *WaypointGetAddOnDefinitionParams) WithContext(ctx context.Context) *WaypointGetAddOnDefinitionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the waypoint get add on definition params
func (o *WaypointGetAddOnDefinitionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the waypoint get add on definition params
func (o *WaypointGetAddOnDefinitionParams) WithHTTPClient(client *http.Client) *WaypointGetAddOnDefinitionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the waypoint get add on definition params
func (o *WaypointGetAddOnDefinitionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddOnDefinitionID adds the addOnDefinitionID to the waypoint get add on definition params
func (o *WaypointGetAddOnDefinitionParams) WithAddOnDefinitionID(addOnDefinitionID string) *WaypointGetAddOnDefinitionParams {
	o.SetAddOnDefinitionID(addOnDefinitionID)
	return o
}

// SetAddOnDefinitionID adds the addOnDefinitionId to the waypoint get add on definition params
func (o *WaypointGetAddOnDefinitionParams) SetAddOnDefinitionID(addOnDefinitionID string) {
	o.AddOnDefinitionID = addOnDefinitionID
}

// WithAddOnDefinitionName adds the addOnDefinitionName to the waypoint get add on definition params
func (o *WaypointGetAddOnDefinitionParams) WithAddOnDefinitionName(addOnDefinitionName *string) *WaypointGetAddOnDefinitionParams {
	o.SetAddOnDefinitionName(addOnDefinitionName)
	return o
}

// SetAddOnDefinitionName adds the addOnDefinitionName to the waypoint get add on definition params
func (o *WaypointGetAddOnDefinitionParams) SetAddOnDefinitionName(addOnDefinitionName *string) {
	o.AddOnDefinitionName = addOnDefinitionName
}

// WithNamespaceID adds the namespaceID to the waypoint get add on definition params
func (o *WaypointGetAddOnDefinitionParams) WithNamespaceID(namespaceID string) *WaypointGetAddOnDefinitionParams {
	o.SetNamespaceID(namespaceID)
	return o
}

// SetNamespaceID adds the namespaceId to the waypoint get add on definition params
func (o *WaypointGetAddOnDefinitionParams) SetNamespaceID(namespaceID string) {
	o.NamespaceID = namespaceID
}

// WriteToRequest writes these params to a swagger request
func (o *WaypointGetAddOnDefinitionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param add_on_definition.id
	if err := r.SetPathParam("add_on_definition.id", o.AddOnDefinitionID); err != nil {
		return err
	}

	if o.AddOnDefinitionName != nil {

		// query param add_on_definition.name
		var qrAddOnDefinitionName string

		if o.AddOnDefinitionName != nil {
			qrAddOnDefinitionName = *o.AddOnDefinitionName
		}
		qAddOnDefinitionName := qrAddOnDefinitionName
		if qAddOnDefinitionName != "" {

			if err := r.SetQueryParam("add_on_definition.name", qAddOnDefinitionName); err != nil {
				return err
			}
		}
	}

	// path param namespace_id
	if err := r.SetPathParam("namespace_id", o.NamespaceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
