// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// HashicorpCloudPacker20230101DeleteBuildResponse hashicorp cloud packer 20230101 delete build response
//
// swagger:model hashicorp.cloud.packer_20230101.DeleteBuildResponse
type HashicorpCloudPacker20230101DeleteBuildResponse interface{}
