// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// HashicorpCloudBoundary20211221UpdateResponse UpdateResponse is a response of the update request.
//
// swagger:model hashicorp.cloud.boundary_20211221.UpdateResponse
type HashicorpCloudBoundary20211221UpdateResponse interface{}
