// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Secrets20231128ServiceAccountImpersonationResponse secrets 20231128 service account impersonation response
//
// swagger:model secrets_20231128ServiceAccountImpersonationResponse
type Secrets20231128ServiceAccountImpersonationResponse struct {

	// service account email
	ServiceAccountEmail string `json:"service_account_email,omitempty"`
}

// Validate validates this secrets 20231128 service account impersonation response
func (m *Secrets20231128ServiceAccountImpersonationResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this secrets 20231128 service account impersonation response based on context it is used
func (m *Secrets20231128ServiceAccountImpersonationResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Secrets20231128ServiceAccountImpersonationResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Secrets20231128ServiceAccountImpersonationResponse) UnmarshalBinary(b []byte) error {
	var res Secrets20231128ServiceAccountImpersonationResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
