// Code generated by go-swagger; DO NOT EDIT.

package consul_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hashicorp/hcp-sdk-go/clients/cloud-consul-service/preview/2020-08-26/models"
)

// ConsulServiceDeleteReader is a Reader for the ConsulServiceDelete structure.
type ConsulServiceDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConsulServiceDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewConsulServiceDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewConsulServiceDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewConsulServiceDeleteOK creates a ConsulServiceDeleteOK with default headers values
func NewConsulServiceDeleteOK() *ConsulServiceDeleteOK {
	return &ConsulServiceDeleteOK{}
}

/*ConsulServiceDeleteOK handles this case with default header values.

A successful response.
*/
type ConsulServiceDeleteOK struct {
	Payload *models.HashicorpCloudConsul20200826DeleteResponse
}

func (o *ConsulServiceDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /consul/2020-08-26/organizations/{location.organization_id}/projects/{location.project_id}/clusters/{id}][%d] consulServiceDeleteOK  %+v", 200, o.Payload)
}

func (o *ConsulServiceDeleteOK) GetPayload() *models.HashicorpCloudConsul20200826DeleteResponse {
	return o.Payload
}

func (o *ConsulServiceDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HashicorpCloudConsul20200826DeleteResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConsulServiceDeleteDefault creates a ConsulServiceDeleteDefault with default headers values
func NewConsulServiceDeleteDefault(code int) *ConsulServiceDeleteDefault {
	return &ConsulServiceDeleteDefault{
		_statusCode: code,
	}
}

/*ConsulServiceDeleteDefault handles this case with default header values.

An unexpected error response.
*/
type ConsulServiceDeleteDefault struct {
	_statusCode int

	Payload *models.GrpcGatewayRuntimeError
}

// Code gets the status code for the consul service delete default response
func (o *ConsulServiceDeleteDefault) Code() int {
	return o._statusCode
}

func (o *ConsulServiceDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /consul/2020-08-26/organizations/{location.organization_id}/projects/{location.project_id}/clusters/{id}][%d] ConsulService_Delete default  %+v", o._statusCode, o.Payload)
}

func (o *ConsulServiceDeleteDefault) GetPayload() *models.GrpcGatewayRuntimeError {
	return o.Payload
}

func (o *ConsulServiceDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GrpcGatewayRuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
