// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpCloudVault20201125DisasterRecoveryNetworkConfig hashicorp cloud vault 20201125 disaster recovery network config
//
// swagger:model hashicorp.cloud.vault_20201125.DisasterRecoveryNetworkConfig
type HashicorpCloudVault20201125DisasterRecoveryNetworkConfig struct {

	// location is the location of the disaster recovery hvn.
	Location *HashicorpCloudInternalLocationLocation `json:"location,omitempty"`

	// network_id is the ID of the network the Vault cluster belongs to.
	NetworkID string `json:"network_id,omitempty"`
}

// Validate validates this hashicorp cloud vault 20201125 disaster recovery network config
func (m *HashicorpCloudVault20201125DisasterRecoveryNetworkConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLocation(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudVault20201125DisasterRecoveryNetworkConfig) validateLocation(formats strfmt.Registry) error {
	if swag.IsZero(m.Location) { // not required
		return nil
	}

	if m.Location != nil {
		if err := m.Location.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("location")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("location")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this hashicorp cloud vault 20201125 disaster recovery network config based on the context it is used
func (m *HashicorpCloudVault20201125DisasterRecoveryNetworkConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLocation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudVault20201125DisasterRecoveryNetworkConfig) contextValidateLocation(ctx context.Context, formats strfmt.Registry) error {

	if m.Location != nil {

		if swag.IsZero(m.Location) { // not required
			return nil
		}

		if err := m.Location.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("location")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("location")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudVault20201125DisasterRecoveryNetworkConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudVault20201125DisasterRecoveryNetworkConfig) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudVault20201125DisasterRecoveryNetworkConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
