---
name: publish-sdk

on: 
  workflow_dispatch:
      inputs:
        service:
          description: 'The service whose SDK needs to be generated'
          required: true
          default: 'cloud-shared'

jobs:
  publish-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout hcp-sdk-go
        uses: actions/checkout@v2
        with:
          ref: main
          path: hcp-sdk-go

      - name: Checkout cloud-api
        uses: actions/checkout@v2
        with:
          repository: hashicorp/cloud-api
          token: ${{ github.token }} # ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          path: cloud-api

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'

      - name: Install dependencies
        run: |
          version=0.25.0
          goos=$(go env GOOS)
          goarch="$(go env GOARCH)"
          download_url="https://github.com/go-swagger/go-swagger/releases/download/v${version}/swagger_${goos}_${goarch}"
          curl -o /usr/local/bin/swagger -L'#' "$download_url"
          chmod +x /usr/local/bin/swagger
          apt-get update -y
          apt-get install -y rsync

      - name: Copy latest cloud-consul-service specs # ${{ github.event.inputs.service }}
        env: 
          SERVICE: cloud-consul-service # ${{ github.event.inputs.service }}
        run: |
          rsync -a $GITHUB_WORKSPACE/cloud-api/specs/"$SERVICE" $GITHUB_WORKSPACE/hcp-sdk-go/temp
          rsync -a $GITHUB_WORKSPACE/cloud-api/specs/cloud-shared $GITHUB_WORKSPACE/hcp-sdk-go/temp
          rsync -a $GITHUB_WORKSPACE/cloud-api/specs/external $GITHUB_WORKSPACE/hcp-sdk-go/temp

      - name: Generate SDK for cloud-consul-service # ${{ github.event.inputs.service }}
        env: 
          SERVICE: cloud-consul-service # ${{ github.event.inputs.service }} 
        run: |
          generate_sdk() {
            service=$1
            stage=$2
            version=$3

            if [ -d "clients/$service/$stage/$version" ]; then \
              echo "Removing original SDK from clients/$service/$stage/$version" && rm -rf "$SCRIPTS_DIR/../clients/$service/$stage/$version"; \
            fi

            echo "Creating target SDK directory: hcp-sdk-go/clients/$service/$stage/$version"
            mkdir -p "../../../clients/$service/$stage/$version"

            rel=("$version"/*.swagger.json)
            spec="${rel[0]}"
            target="../../../clients/$service/$stage/$version"

            echo "Generating SDK for $service(stage: $stage, version: $version)"
            swagger generate client \
              -f "$spec" \
              -t "$target" \
              -q \
              -A "$service"
          }

          cd hcp-sdk-go/temp/"$SERVICE"

          transformer=../../../cmd/transform-swagger
          shared_specs=../../../temp/cloud-shared
          external_spec=../../../temp/external/external.swagger.json

          for d in *; do
            if [[ -d "$d" ]]; then
              stage=$d

              cd "$stage"
            fi

            for f in *; do
              if [[ -d "$f" ]]; then
                version=$f
                service_spec=("$version"/*.swagger.json)

                echo "Transforming specs for $SERVICE (stage: $stage, version: $version) in preparation for SDK generation"
                go run "$transformer" \
                  -service="${service_spec[0]}" \
                  -shared="$shared_specs" \
                  -external="$external_spec"
                
                generate_sdk "$SERVICE" "$stage" "$version"
              fi
            done
          done

          cd ../../..

          echo "Regenerating shared external SDK models"
          swagger generate model \
            -f ./temp/external/external.swagger.json \
            -t ./clients/cloud-shared/v1 \
            -q

          echo "SDK for $SERVICE generated!"

          rm -rf ./temp

      - name: Open PR
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          token: ${{ github.token }} # ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          path: hcp-sdk-go
          branch: auto-update-service-sdk
          committer: Brenna Hewer-Darroch <21015366+bcmdarroch@users.noreply.github.com>
          commit-message: Update cloud-consul-service SDK # ${{ github.event.inputs.service }} 
          title: '[auto] Update cloud-consul-service SDK' # ${{ github.event.inputs.service }} 
          body: |
            This is an auto-generated PR created as part of the public SDK pipeline.

            Changes:
            - Pulled the latest public service SDK from cloud-consul-service 
          # ${{ github.event.inputs.service }} 
          delete-branch: true