---
name: publish-sdk

on: 
  workflow_dispatch:
      inputs:
        service:
          description: 'The service whose SDK needs to be generated'
          required: true

jobs:
  publish-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Set env service branch
        run: echo "SERVICE_BRANCH=auto-update-${{ github.event.inputs.service }}-sdk" >> $GITHUB_ENV

      - name: Checkout hcp-sdk-go
        uses: actions/checkout@v2
        with:
          ref: main
          path: hcp-sdk-go

      - name: Checkout cloud-api
        uses: actions/checkout@v2
        with:
          repository: hashicorp/cloud-api
          ref: auto-update-${{ github.event.inputs.service }}-specs
          token: ${{ secrets.HCP_SDK_PIPELINE_TOKEN }}
          path: cloud-api

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'

      - name: Install dependencies
        run: |
          version=0.30.2
          goos=$(go env GOOS)
          goarch="$(go env GOARCH)"
          download_url="https://github.com/go-swagger/go-swagger/releases/download/v${version}/swagger_${goos}_${goarch}"
          curl -o /usr/local/bin/swagger -L'#' "$download_url"
          chmod +x /usr/local/bin/swagger
          sudo apt-get update -y
          sudo apt-get install -y rsync

      - name: Copy latest service specs
        env: 
          SERVICE: ${{ github.event.inputs.service }}
        run: |
          rsync -a $GITHUB_WORKSPACE/cloud-api/specs/"$SERVICE" $GITHUB_WORKSPACE/hcp-sdk-go/temp
          rsync -a $GITHUB_WORKSPACE/cloud-api/specs/cloud-shared $GITHUB_WORKSPACE/hcp-sdk-go/temp
          rsync -a $GITHUB_WORKSPACE/cloud-api/specs/external $GITHUB_WORKSPACE/hcp-sdk-go/temp

      - name: Generate SDK for service
        env: 
          SERVICE: ${{ github.event.inputs.service }}
        run: |
          cd $GITHUB_WORKSPACE/hcp-sdk-go
          ./scripts/gen-go-service-sdk.sh $SERVICE
          rm -rf $GITHUB_WORKSPACE/hcp-sdk-go/temp

      - name: Create branch with updated service SDK
        run: |
          cd $GITHUB_WORKSPACE/hcp-sdk-go
          git config user.name "HashiCorp Cloud Services"
          git config user.email "59096967+hashicorp-cloud@users.noreply.github.com"
          service_branch_exists="$(git ls-remote --heads origin ${{ env.SERVICE_BRANCH }})"
          [[ -n $service_branch_exists ]] && git push origin --delete ${{ env.SERVICE_BRANCH }}
          git checkout -b ${{ env.SERVICE_BRANCH }}
          git add clients/${{ github.event.inputs.service }}/*
          git commit -m "Update ${{ github.event.inputs.service }} SDK"
          git push --set-upstream origin ${{ env.SERVICE_BRANCH }}    
          
      - name: Open PR
        run: |
          cd $GITHUB_WORKSPACE/hcp-sdk-go
          gh pr create --title "$PR_TITLE" --body "$PR_BODY" -H "$PR_SOURCE" -B "$PR_TARGET"
        env:
          PR_TITLE: "[auto] Update ${{ github.event.inputs.service }} SDK"
          PR_BODY: "This is an auto-generated PR created as part of the public SDK pipeline to update the SDK for ${{ github.event.inputs.service }}."
          PR_SOURCE: "${{ env.SERVICE_BRANCH }}"
          PR_TARGET: "main"
          GITHUB_TOKEN: ${{ secrets.HCP_SDK_PIPELINE_TOKEN }} 
