name: Test

permissions:
  contents: write

on: 
  pull_request:
  push: 
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  test:
    name: Run Unit Tests and Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          cache: true
          go-version-file: 'go.mod'
          cache-dependency-path: go.sum

      - name: Install Dependencies
        run: |
          go mod download
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2
          go mod tidy

      - name: Run Tests
        run: make test-ci

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: Test Coverage
          path: coverage.html
