name: Test

permissions:
  contents: write

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  test:
    name: Run Unit Tests and Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          cache: true
          go-version-file: 'go.mod'
          cache-dependency-path: go.sum

      - name: Install Dependencies
        run: |
          go mod download
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.6
          go mod tidy

      - name: Run Tests
        run: make test-ci

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: Test Coverage
          path: coverage.html
