name: Test

permissions:
  contents: write

on: 
  pull_request:
  push: 
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  test:
    name: Run Unit Tests and Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          cache: true
          go-version-file: 'go.mod'
          cache-dependency-path: go.sum

      - name: Install Dependencies
        run: |
          go mod download
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.49.0
          go mod tidy

      - name: Run Tests
        run: make test-ci

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: Test Coverage
          path: coverage.html
