name: Test

permissions:
  contents: write

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  test:
    name: Run Unit Tests and Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          cache: true
          go-version-file: 'go.mod'
          cache-dependency-path: go.sum

      - name: Install Dependencies
        run: |
          go mod download
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.6
          go mod tidy

      - name: Run Tests
        run: make test-ci

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: Test Coverage
          path: coverage.html
